
INSERT INTO EMPLOYEE(EMPLOYEE_ID, EMPLOYEE_ROLE, EMPLOYEE_FIRST_NAME, 
                    EMPLOYEE_LAST_NAME, EMPLOYEE_HIRE_DATE, EMPLOYEE_TERMINATION_DATE, EMPLOYEE_SALARY) VALUES
( NULL, 'Manager' , 'Joe', 'McCarwash', '2021-01-01', NULL, 123456.99),
( NULL, 'Accountant' , 'Jane', 'Moneyhandler', '2021-01-01', NULL, 79999.23),
( NULL, 'Washer' , 'Jim', 'Buffer', '2021-01-01', '2021-02-02', 40000.24),
( NULL, 'Washer', 'Jack', 'Waxer', '2021-01-01', NULL, 40000.24);


INSERT INTO CUSTOMER(CUSTOMER_ID, CUSTOMER_FIRST_NAME, CUSTOMER_LAST_NAME) VALUES
( NULL, 'Washma' , 'Car'),
( NULL, 'Cleanma' , 'Trunk');


INSERT INTO WASH(WASH_ID, WASH_TYPE, WASH_STATUS, EMPLOYEE_ID, CUSTOMER_ID) VALUES 
(
NULL, 
'basic', 
1, 
(SELECT EMPLOYEE_ID FROM EMPLOYEE WHERE EMPLOYEE_FIRST_NAME = 'Jack'), 
(SELECT CUSTOMER_ID FROM CUSTOMER WHERE CUSTOMER_FIRST_NAME = 'Washma')
),
(NULL, 
'premium', 
1, 
(SELECT EMPLOYEE_ID FROM EMPLOYEE WHERE EMPLOYEE_FIRST_NAME = 'Jack'), 
(SELECT CUSTOMER_ID FROM CUSTOMER WHERE CUSTOMER_FIRST_NAME = 'Washma')
),
(
NULL, 
'executive', 
0, 
(SELECT EMPLOYEE_ID FROM EMPLOYEE WHERE EMPLOYEE_FIRST_NAME = 'Jim'), 
(SELECT CUSTOMER_ID FROM CUSTOMER WHERE CUSTOMER_FIRST_NAME = 'Cleanma')
);

INSERT INTO INVOICE(INVOICE_ID, WASH_ID, CUSTOMER_ID, INVOICE_TOTAL, INVOICE_BALANCE, CREATED_DATE, PAID_DATE) VALUES
(NULL, 1, 
(SELECT CUSTOMER_ID FROM CUSTOMER WHERE CUSTOMER_FIRST_NAME = 'Washma'),
70.00, 70.00, '2021-12-08', NULL),
(NULL, 2, 
(SELECT CUSTOMER_ID FROM CUSTOMER WHERE CUSTOMER_FIRST_NAME = 'Washma'),
70.00, 0, '2021-11-08', '2021-11-09'),
(NULL, 3, 
(SELECT CUSTOMER_ID FROM CUSTOMER WHERE CUSTOMER_FIRST_NAME = 'Cleanma'),
140.00, 70.00, '2021-12-08', NULL);

INSERT INTO PAYMENT(PAYMENT_ID, INVOICE_ID, PAYMENT_AMOUNT) VALUES
(NULL, 2, 70),
(NULL, 3, 70);