<<<<<<< HEAD
INSERT INTO EMPLOYEE(EMPLOYEE_ID, EMPLOYEE_ROLE, EMPLOYEE_FIRST_NAME, 
                    EMPLOYEE_LAST_NAME, EMPLOYEE_HIRE_DATE, EMPLOYEE_TERMINATION_DATE, EMPLOYEE_SALARY) VALUES
( NULL, 'Manager' , 'Joe', 'McCarwash', '2021-01-01', NULL, 123456.99),
( NULL, 'Accountant' , 'Jane', 'Moneyhandler', '2021-01-01', NULL, 79999.23),
( NULL, 'Washer' , 'Jim', 'Buffer', '2021-01-01', '2021-02-02', 40000.24),
( NULL, 'Washer', 'Jack', 'Waxer', '2021-01-01', NULL, 40000.24);

INSERT INTO WASH (WASH_ID, WASH_TYPE, WASH_PRICE, WASH_STATUS, EMPLOYEE_ID, CUSTOMER_ID) VALUES 
(NULL, 'basic', 13.99, 1, (SELECT EMPLOYEE_ID from EMPLOYEE where EMPLOYEE_ID = 01), (SELECT CUSTOMER_ID from CUSTOMER where CUSTOMER_ID = 01)),
(NULL, 'basic', 13.99, 0, (SELECT EMPLOYEE_ID from EMPLOYEE where EMPLOYEE_ID = 02), (SELECT CUSTOMER_ID from CUSTOMER where CUSTOMER_ID = 02)),
(NULL, 'basic', 13.99, 0, (SELECT EMPLOYEE_ID from EMPLOYEE where EMPLOYEE_ID = 01), (SELECT CUSTOMER_ID from CUSTOMER where CUSTOMER_ID = 03)),
(NULL, 'premium', 69.99, 0, (SELECT EMPLOYEE_ID from EMPLOYEE where EMPLOYEE_ID = 02), (SELECT CUSTOMER_ID from CUSTOMER where CUSTOMER_ID = 04)),
(NULL, 'executive', 420.99, 0, (SELECT EMPLOYEE_ID from EMPLOYEE where EMPLOYEE_ID = 03), (SELECT CUSTOMER_ID from CUSTOMER where CUSTOMER_ID = 05)),
(NULL, 'executive', 420.99, 0, (SELECT EMPLOYEE_ID from EMPLOYEE where EMPLOYEE_ID = 04), (SELECT CUSTOMER_ID from CUSTOMER where CUSTOMER_ID = 06));