DROP TABLE IF EXISTS EMPLOYEE;

CREATE TABLE EMPLOYEE
(
    EMPLOYEE_ID INT PRIMARY KEY AUTO_INCREMENT,
    EMPLOYEE_ROLE VARCHAR(10),
    EMPLOYEE_FIRST_NAME VARCHAR(15),
    EMPLOYEE_LAST_NAME VARCHAR(25),
    EMPLOYEE_HIRE_DATE DATE,
    EMPLOYEE_TERMINATION_DATE DATE,
    EMPLOYEE_SALARY DECIMAL (8,2)
    
);