DROP TABLE IF EXISTS EMPLOYEE;

CREATE TABLE EMPLOYEE
(
    EMPLOYEE_ID INT PRIMARY KEY AUTO_INCREMENT,
    EMPLOYEE_ROLE VARCHAR(10),
    EMPLOYEE_FIRST_NAME VARCHAR(15),
    EMPLOYEE_LAST_NAME VARCHAR(25),
    EMPLOYEE_HIRE_DATE DATE,
    EMPLOYEE_TERMINATION_DATE DATE,
    EMPLOYEE_SALARY DECIMAL (8,2)
);    

DROP TABLE IF EXISTS WASH;

CREATE TABLE WASH (
    WASH_ID INT PRIMARY KEY AUTO_INCREMENT,
    WASH_TYPE ENUM('basic', 'premium', 'executive'),
    WASH_PRICE ENUM(13.99, 69.99, 420.99),
    WASH_STATUS BOOL NOT NULL DEFAULT 0,
    FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE(EMPLOYEE_ID),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID)   
);